apiVersion: v1
kind: Namespace
metadata:
  name: webapps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: boardgame
  replicas: 2 
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
# nishargsoni/boardgame:latest

---

apiVersion: v1 
kind: Service 
metadata: 
  name: boardgame-ssvc
  namespace: webapps
spec:
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: NodePort
